# Generated by Django 6.0.2 on 2026-02-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclub',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
